apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres-db
  namespace: banco-galicia
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  PGDATA: /data/pgdata

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-config-cm
  namespace: banco-galicia
data:
  init.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
        CREATE DATABASE entitystore;
        CREATE USER fluxdb WITH ENCRYPTED PASSWORD 'fluxdbpwd';
        GRANT ALL PRIVILEGES ON DATABASE entitystore TO fluxdb;
    EOSQL
 
    psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "entitystore" <<-EOSQL
        GRANT ALL PRIVILEGES ON SCHEMA public TO fluxdb;
        GRANT CREATE ON SCHEMA public TO fluxdb;
    EOSQL